### ISSUE TITLE
Can not migrate to gradle 4.X

### ISSUE THREAD

**Issue by DenisYelkin** [brooth/androjeta#1]
I tryed to migrate on new android gradle plugin 3.0.1 and it require to update gradle version to 4.1 at least (I prefere to use 4.3).
By migrating I solved a lot of issues [(documentation link):](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#annotationProcessor_config)

1. You have to remove using 'android-apt' plugin
2. Arguments for annotation processor passing by another way:
```
android {
  //....
  javaCompileOptions {
    annotationProcessorOptions {
      arguments = ['jetaProperties': "$project.projectDir/src/main/java/jeta.properties".toString()]
    }
  }
}
```
3. You have to replace command for dependency: instead `apt` you have to use `annotationProcessor`

But after all of this i stucked on next error:
```
Note: processing. round: 1

 FAILED
:myproject:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myproject:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: Failed to load meta alias annotation javax.inject.Inject
```

Can you please update [installation guide](http://brooth.github.io/jeta/guide/androjeta/install.html).

**Comment by brooth** [comment]
`Failed to load meta alias annotation javax.inject.Inject` basically means that the library doesn't get `jetaProperties` arg so can't parse `jeta.properties` that leads to thinking that `com.neenbedankt.gradle.plugins:android-apt` plugin doesn't support the new-argument-passing-way. In this case, the issue has nothing to do with jeta. Through, you can load `jeta.properties` alternative way:

```
compileJava {
    options.sourcepath = files('src/main/java')
}
```

please, check http://brooth.github.io/jeta/guide/config.html out for details.

**Comment by DenisYelkin** [comment]
As I described arguments might be passed just by alternative way for new gradle version:
```
android {
  //....
  javaCompileOptions {
    annotationProcessorOptions {
      arguments = ['jetaProperties': "$project.projectDir/src/main/java/jeta.properties".toString()]
    }
  }
}
```
This way works. Because without this I got another issue that directly says about missing `jeta.properties` file (it was about failing to process `@FindView` annotation).

Adding
```
compileJava {
    options.sourcepath = files('src/main/java')
}
```
did not help at all.

Full stack of my issue looks like this:
```
Caused by: java.lang.RuntimeException: Failed to load meta alias annotation javax.inject.Inject
	at org.brooth.jeta.apt.processors.InjectProcessor.collectElementsAnnotatedWith(InjectProcessor.java:461)
	at org.brooth.jeta.apt.JetaProcessor.removeDisabledProcessors(JetaProcessor.java:268)
	at org.brooth.jeta.apt.JetaProcessor.process(JetaProcessor.java:231)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 52 more
Caused by: java.lang.ClassNotFoundException: javax.inject.Inject
	at org.brooth.jeta.apt.processors.InjectProcessor.collectElementsAnnotatedWith(InjectProcessor.java:454)
	... 62 more
```

Finally I found two solutions for myself:

1. Set `includeCompileClasspath false` for annotation processor options. But as described [here](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#disable_the_annotation_processor_error_check) it is just enabling old behaviour and this way is not recommended and will be removed in future.
2. I removed using `javax.inject.*` evrywhere in my project and in `jeta.properties` file. Instead I used alternative annotations from `org.brooth.jeta.inject.*`

So it really looks like an issue with resolving dependency for `javax.inject` library.

FYI `com.neenbedankt.gradle.plugins:android-apt` no more longer need to be used. As I described at first time: you have to remove using 'android-apt' plugin ([link](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#annotationProcessor_config))
